### ISSUE TITLE
Allow Symfony 4

### ISSUE THREAD

**Issue by robertfausk** [GGGGino/WordBundle#1]
Currently required version is to low:
```ggggino/wordbundle v1.0.6 requires symfony/framework-bundle ~2.6|~3.0```

In my composer.json I have:
```"symfony/framework-bundle": "~4.0"```

**Comment by GGGGino** [comment]
Sorry for the delay.
Here is the fix: 2a1ace7

**Comment by robertfausk** [comment]
No problem. Thx.
